// <auto-generated />
using System;
using BankingSparplanSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankingSparplanSystem.Infrastructure.Migrations
{
    [DbContext(typeof(SparplanDbContext))]
    partial class SparplanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankingSparplanSystem.Domain.Entitaeten.Kunde", b =>
                {
                    b.Property<int>("KundeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KundeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KundeId");

                    b.ToTable("Kunden");
                });

            modelBuilder.Entity("BankingSparplanSystem.Domain.Entitaeten.Sparplan", b =>
                {
                    b.Property<int>("SparplanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SparplanId"));

                    b.Property<decimal>("BarrenMenge")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("GewünschteSpargrenze")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<bool>("IstAktiviert")
                        .HasColumnType("bit");

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.Property<int>("MonatlicheZahlung")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Stornierungsdatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.Property<DateTime>("Vertragsdatum")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Zielbetrag")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.HasKey("SparplanId");

                    b.HasIndex("KundeId");

                    b.ToTable("Sparplaene");
                });

            modelBuilder.Entity("BankingSparplanSystem.Domain.Entitaeten.Sparplan", b =>
                {
                    b.HasOne("BankingSparplanSystem.Domain.Entitaeten.Kunde", "Kunde")
                        .WithMany("Sparplaene")
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kunde");
                });

            modelBuilder.Entity("BankingSparplanSystem.Domain.Entitaeten.Kunde", b =>
                {
                    b.Navigation("Sparplaene");
                });
#pragma warning restore 612, 618
        }
    }
}
