<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BankingSparplanSystem.API\BankingSparplanSystem.API.csproj" />
    <ProjectReference Include="..\BankingSparplanSystem.Infrastructure\BankingSparplanSystem.Infrastructure.csproj" />
  </ItemGroup>

</Project>
